---
- import_tasks: check_vars.yml

- ansible.builtin.import_tasks: uninstall.yml
  when: uninstall_redis | default(false)
  tags:
    - uninstall

- import_tasks: download.yml
  when: redis_install_from_source
  tags:
    - download

- import_tasks: dependencies.yml
  when: redis_install_from_source
  tags:
    - install

- import_tasks: install.yml
  when: redis_install_from_source
  tags:
    - install

- import_tasks: install_from_repo.yml
  when: not redis_install_from_source
  tags:
    - install

- import_tasks: server.yml
  when: not redis_sentinel
  tags:
    - config

- import_tasks: sentinel.yml
  when: redis_sentinel
  tags:
    - config

- import_tasks: local_facts.yml
  when: redis_local_facts|bool
